package pipass

import (
	"bytes"
	"errors"
	"fmt"
	"reflect"

	"github.com/dave/jennifer/jen"
	"github.com/thumbrise/pipass/generator"
)

var ErrNotStruct = errors.New("not a struct")

//nolint:cyclop,funlen,gocognit
func Compile(packageName string, root any, nodes ...any) ([]byte, error) {
	f := jen.NewFile(packageName)
	f.HeaderComment("Code generated by thumbrise/pipass; DO NOT EDIT.")

	registry := make(map[string]bool)
	typesToProcess := make([]reflect.Type, 0)

	rType := reflect.TypeOf(root)
	if rType == nil {
		return nil, fmt.Errorf("%w: root is nil", ErrNotStruct)
	}

	for rType.Kind() == reflect.Pointer {
		rType = rType.Elem()
	}

	if rType.Kind() != reflect.Struct {
		return nil, fmt.Errorf("%w root(%s)", ErrNotStruct, rType.Kind())
	}

	registry[rType.PkgPath()+"."+rType.Name()] = true
	typesToProcess = append(typesToProcess, rType)

	for _, n := range nodes {
		t := reflect.TypeOf(n)
		if t == nil {
			continue
		}

		for t.Kind() == reflect.Pointer {
			t = t.Elem()
		}

		if t.Kind() == reflect.Struct && !registry[t.PkgPath()+"."+t.Name()] {
			registry[t.PkgPath()+"."+t.Name()] = true
			typesToProcess = append(typesToProcess, t)
		}
	}

	for _, t := range typesToProcess {
		entity := &generator.Entity{
			Name:   t.Name(),
			Fields: make([]generator.Field, 0, t.NumField()),
		}

		for i := range t.NumField() {
			field := t.Field(i)
			if field.PkgPath != "" {
				continue
			}

			fieldInfo := generator.Field{
				Name: field.Name,
				Kind: field.Type.Kind().String(),
			}

			if field.Type.Kind() == reflect.Slice || field.Type.Kind() == reflect.Map {
				elemType := field.Type.Elem()
				for elemType.Kind() == reflect.Pointer {
					elemType = elemType.Elem()
				}

				fieldInfo.ElemTypeName = elemType.Name()
				if field.Type.Kind() == reflect.Slice && registry[elemType.PkgPath()+"."+elemType.Name()] {
					fieldInfo.IsNode = true
				}
			}

			entity.Fields = append(entity.Fields, fieldInfo)
		}

		gen := generator.NewGenerator(f)
		gen.GenerateFields(entity)
	}

	buf := bytes.NewBuffer(nil)
	if err := f.Render(buf); err != nil {
		return nil, fmt.Errorf("%w: %w", generator.ErrRender, err)
	}

	return buf.Bytes(), nil
}
