#schema: https://taskfile.dev/schema.json
version: '3.17'

tasks:
  lint:
    desc: Run lint with auto-fix where possible (dev workflow)
    cmds:
      - docker run --rm -v "$(pwd):/repo" -w /repo thumbrise/commitlint-scope:latest-alpine run --from main --to HEAD
      - golangci-lint run --fix

  test:
    desc: Run tests
    cmds:
      - go test ./... -v -tags=test
      - go test ./... -v -tags=test -run=NONE -bench=. -benchmem
